-- MySQL Script generated by MySQL Workbench
-- 02/03/15 16:33:45
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mvc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mvc` ;

-- -----------------------------------------------------
-- Table `mvc`.`type_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`type_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `type_user_id` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_type_user_idx` (`type_user_id` ASC),
  CONSTRAINT `fk_User_type_user`
    FOREIGN KEY (`type_user_id`)
    REFERENCES `mvc`.`type_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`gender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `format` VARCHAR(255) NOT NULL,
  `total_units` INT NOT NULL,
  `year` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NOT NULL,
  `gender_id` INT NOT NULL,
  `status` TINYINT NOT NULL,
  `rented_units` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_movie_gender1_idx` (`gender_id` ASC),
  CONSTRAINT `fk_movie_gender1`
    FOREIGN KEY (`gender_id`)
    REFERENCES `mvc`.`gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `ife` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc`.`client_has_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`client_has_movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  `rented_units` INT NOT NULL,
  `total` DOUBLE NOT NULL,
  `date` DATE NOT NULL,
  `devolution_date` DATE NOT NULL,
  `is_rented` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `client_id`, `movie_id`),
  INDEX `fk_client_has_movie_movie1_idx` (`movie_id` ASC),
  INDEX `fk_client_has_movie_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_client_has_movie_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mvc`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_movie_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mvc`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mvc`.`type_user`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvc`;
INSERT INTO `mvc`.`type_user` (`id`, `name`) VALUES (1, 'ADMINISTRADOR');
INSERT INTO `mvc`.`type_user` (`id`, `name`) VALUES (2, 'EMPLEADO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mvc`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvc`;
INSERT INTO `mvc`.`User` (`id`, `username`, `password`, `type_user_id`, `email`, `name`, `last_name`, `status`) VALUES (1, 'admin', 'admin', 1, 'admin@gmail.com', 'Admin', 'Admin', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mvc`.`gender`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvc`;
INSERT INTO `mvc`.`gender` (`id`, `name`) VALUES (1, 'ACCION');
INSERT INTO `mvc`.`gender` (`id`, `name`) VALUES (2, 'COMEDIA');
INSERT INTO `mvc`.`gender` (`id`, `name`) VALUES (3, 'TERROR');
INSERT INTO `mvc`.`gender` (`id`, `name`) VALUES (4, 'SUSPENSO');
INSERT INTO `mvc`.`gender` (`id`, `name`) VALUES (5, 'DRAMA');
INSERT INTO `mvc`.`gender` (`id`, `name`) VALUES (6, 'INFANTIL');

COMMIT;

